#ifndef lax_solver_h
#define lax_solver_h

#define nn 2
#define mm 1
#define nm 3
#define NN 10
#define k_max 5000
#define tol 0.001000000000000
#define in_engineering 0
#define MEASURE_TIME 1
#define SCALAR_RHO
#define rho 15.000000000000000
#define rho_i 0.066666666666667


typedef struct {
    double z[NN*nm]; // Optimal z
    double v[NN*nm]; // Optimal v
    double lambda[NN*nm]; // Optimal lambda
    double update_time;
    double solve_time;
    double polish_time;
    double run_time;
} solution;

#ifdef CONF_MATLAB

void laxMPC_ADMM(double *pointer_x0, double *pointer_xr, double *pointer_ur, double *u_opt, double *pointer_k, double *e_flag, double *z_opt, double *v_opt, double *lambda_opt, double *update_time, double *solve_time, double *polish_time, double *run_time);

#else

void laxMPC_ADMM(double *pointer_x0, double *pointer_xr, double *pointer_ur, double *u_opt, int *pointer_k, int *e_flag, solution *sol);

#endif

#endif

// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies

// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies
